spring.application.name=duranstuff
spring.datasource.url=jdbc:postgresql://167.86.74.77:5433/duranstuff
spring.datasource.username=dev
spring.datasource.password=dev
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true